from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from fastapi import FastAPI, status

app = FastAPI()
userData = []
id = 1

class Password(BaseModel):
    domain: str | None = None
    username: str | None = None
    password: str | None = None
    notes: str | None = None


@app.get("/")
def root():
    return {
        "message": "Hello World!!",   
        "url": "https://github.com/PasscodesApp",
        "backend-dev": "https://github.com/jainil63"
    }


@app.post("/passwords", status_code=status.HTTP_201_CREATED)
def get_password(passworditem: Password):
    password = passworditem.dict()
    global id
    password['id'] = id  # In real application, this would be generated by the database
    id += 1
    userData.append(password)
    return password

@app.get("/passwords")
def list_passwords():
    return userData