from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from fastapi import FastAPI, status

app = FastAPI()

class Password(BaseModel):
    domain: str | None = None
    username: str | None = None
    password: str | None = None
    notes: str | None = None


@app.get("/")
def root():
    return {
        "message": "Hello World!!",
        "url": "https://github.com/PasscodesApp"
    }


@app.post("/passwords", status_code=status.HTTP_201_CREATED)
def get_password(passworditem: Password):
    password = passworditem.dict()
    password['id'] = 1  # In real application, this would be generated by the database
    return JSONResponse(content=password)
